services:
  mapstack:
    image: codingkiwi/mapstack:1
    ports:
      - 80:80
      - 8080:8080

  photon:
    image: codingkiwi/mapstack-photon:!
    volumes:
      - ./var/photon:/app/photon_data
    environment:
      MANAGED: false
      COUNTRY: "is"

  versatiles:
    image: codingkiwi/mapstack-versatiles:1
    volumes:
      - ./var/versatiles:/app/versatiles_data
    environment:
      MANAGED: false
      BBOX: "13.091,52.334,13.74,52.676"

  graphhopper:
    image: codingkiwi/mapstack-graphhopper:1
    volumes:
      - ./var/graphhopper:/app/graphhopper_data
    environment:
      MANAGED: false
      REGION: "europe/iceland"

  valkey:
    image: valkey/valkey:9
