services:
  mapstack:
    image: codingkiwi/mapstack
    ports:
      - 80:80
      - 8080:8080

  photon:
    image: codingkiwi/mapstack-photon
    volumes:
      - ./var/photon:/app/photon_data

  versatiles:
    image: codingkiwi/mapstack-versatiles
    volumes:
      - ./var/versatiles:/app/versatiles_data

  graphhopper:
    image: codingkiwi/mapstack-graphhopper
    volumes:
      - ./var/graphhopper:/app/graphhopper_data

  valkey:
    image: valkey/valkey:9
